kind: Deployment
apiVersion: apps/v1
metadata:
  name: kuard
spec:
  template:
    metadata:
      name: testing-deployment
      labels:
        run: kuard
    spec:
      containers:
        - name: kuard
          image: gcr.io/kuar-demo/kuard-amd64:blue
  selector:
    matchLabels:
      run: kuard
  replicas: 4
